### ISSUE TITLE
Warning about native access

### ISSUE THREAD

**Issue by JohannesBeranek** [lopcode/vips-ffm#56] opened 2024-09-20 17:24 UTC
jextract code triggers a warning about needing a special flag in the future, see https://cr.openjdk.org/~asotona/JDK-8308753-preview/api/java.base/java/lang/foreign/SymbolLookup.html (JDK 22 docs about SymbolLookup.libraryLookup):
```
libraryLookup is a restricted method of the Java platform.
Programs can only use libraryLookup when access to restricted methods is enabled.
Restricted methods are unsafe, and, if used incorrectly, might crash the JVM or result in memory corruption.
```

https://openjdk.org/jeps/472
```
To enable native access for all code on the class path, use the following command-line option:

java --enable-native-access=ALL-UNNAMED
```

Besides a nice red message in IntelliJ I think this isn't a big issue right now, but it will probably become one in a few JDK versions

**Comment by lopcode** [comment] 2024-09-20 21:52
I *think* this is just in the dev environment - the packaged Jars get a manifest entry enabling native access: https://github.com/lopcode/vips-ffm/blob/main/core/build.gradle.kts#L68

Which module shows this for you in IntelliJ?

**Comment by JohannesBeranek** [comment] 2024-09-21 15:01
```
WARNING: A restricted method in java.lang.foreign.SymbolLookup has been called
WARNING: java.lang.foreign.SymbolLookup::libraryLookup has been called by app.photofox.vipsffm.VipsLibLookup in an unnamed module
WARNING: Use --enable-native-access=ALL-UNNAMED to avoid a warning for callers in this module
WARNING: Restricted methods will be blocked in a future release unless native access is enabled
```

This is actually the message I get in the intelliJ console output.

"Which module shows this for you in IntelliJ?"

I'm not working with java modules if you mean that?

<img width="895" alt="image" src="https://github.com/user-attachments/assets/1eb21e5f-f0e5-4d79-a443-e8bed0b97d55">

**Comment by JohannesBeranek** [comment] 2024-09-25 08:55
This is unfortunately still an issue even with the latest version (0.5.6). While it's currently only a warning, I fear it might break our prod system at some point when upgrading JDK versions (we've had a similar, though not the same, issue around JDK 14 with Jackson serializing java date types)

**Comment by JohannesBeranek** [comment] 2024-09-25 09:08
Yes, correct.
I know that I can set that flag to prevent the warning, but the issue is that java tends to deprecate and then remove these things, and setting flags for foreign builders (various frameworks for example) is often not that easy when they don't use maven, gradle or ant. Also, we've been using FFM for something else already, and I didn't have that issue, so I thought it might have been something easily fixable?

**Comment by lopcode** [comment] 2024-09-25 09:33
Agree with you that this needs to be fixed - what's confusing me is the build process already includes a flag in the manifest of the built Jar setting the "enable native access" flag, which I thought was the correct way to fix it.

I'll try to reproduce locally later today and investigate

**Comment by lopcode** [comment] 2024-09-25 22:54
I understand this problem a bit better now. Setting the manifest entry won't work because (I think) it needs to be set on the final executable Jar.

Instead, I've added a paragraph in the [README](https://github.com/lopcode/vips-ffm?tab=readme-ov-file#usage) saying you need to set `--enable-native-acccess=ALL-UNNAMED`.

In the future, this library will export a Java module meaning you can switch to `--enable-native-acccess=app.photofox.vipsffm` - but that seems fiddly to set up and difficult to test, so one for another day.

**Comment by JohannesBeranek** [comment] 2024-09-26 16:09
Thanks! Feel free to close this, as I can't really verify / test it (I saw you already added the module to 0.5.9 going by the release notes).

**Comment by lopcode** [comment] 2024-09-26 22:24
The library now defines a module as `app.photofox.vipsffm` but tooling doesn't seem to support it very well - ShadowJar strips module-info classes out so I can't even get `--enable-native-access=app.photofox.vipsffm` to work for me locally. Going to close this and come back to it if tooling improves.

**Closed by lopcode** 2024-09-26 22:24 UTC
Labels: question
